# env.yaml
mongodb:
  host: $DATABASE_HOST
  username: root
  password: $DB_PASSWORD
  database: youtube_db
  collections:
    playlists: playlists
    videoids: videoids
    commentvideo: commentvideo
    statics: statics

mysql:
  host: $DATABASE_HOST
  username: root
  password: $DB_PASSWORD
  database: youtube_db