# env.yaml
mongodb:
  host: localhost
  username: root
  database: youtube_db
  collections:
    playlists: playlists
    videoids: videoids
    commentvideo: commentvideo
    statics: statics

mysql:
  host: localhost
  username: root
  database: youtube_db