# env.yaml
mongodb:
  host: $DATABASE_HOST
  username: root
  password: $DB_PASSWORD
  database: youtube_db
  collections:
    playlists: playlists
    videoids_rapvie: videoids_rapvie
    videoids_nala: videoids_nala

mysql:
  host: $DATABASE_HOST
  username: root
  password: $DB_PASSWORD
  database: youtube_db